// Diccionario i18n ES/EN. Portado del prototipo + claves nuevas para cuenta/admin.
export type Lang = 'es' | 'en';

export const DICT = {
  es: {
    topbar: 'Fabricado a mano en el taller · Piezas a medida bajo pedido',
    nav_home: 'Inicio', nav_catalog: 'Catálogo', nav_about: 'El taller', nav_bespoke: 'Hecho a medida', nav_contact: 'Contacto',
    hero_kicker: 'Carpintería metálica · desde 2013', hero_title_1: 'Acero y madera', hero_title_2: 'con oficio.',
    hero_sub: 'Muebles de estilo industrial hechos a mano, pieza por pieza. Diseñamos y fabricamos a tu medida.',
    hero_cta1: 'Ver catálogo', hero_cta2: 'Pedir a medida',
    cat_kicker: 'Colección', cat_title: 'Explora por categoría',
    feat_kicker: 'Selección', feat_title: 'Piezas destacadas', feat_link: 'Ver todo el catálogo', from: 'Desde', view_piece: 'Ver pieza',
    arband_kicker: 'Realidad aumentada', arband_title: 'Prueba cómo se vería en tu espacio ideal', arband_sub: 'Coloca cualquier pieza de Alvarsa en tu sala con la cámara de tu dispositivo y comprueba medidas, proporción y estilo antes de encargarla.', arband_cta: 'Probar con realidad aumentada',
    moment_kicker: 'Pieza del mes', moment_title: 'Nuestra selección', moment_sub: 'Piezas que definen el oficio del taller. Comodidad y estructura que envejecen bien.', moment_cta: 'Ver pieza',
    craft_quote: '"Si aguanta el peso del taller, aguanta toda una vida en tu casa."', craft_by: '— El equipo de Alvarsa',
    footer_addr: 'Cra. 50 #38-24, Itagüí, Antioquia', footer_rights: '© 2026 Alvarsa. Todos los derechos reservados.',
    footer_l_email: 'Email', footer_l_phone: 'Teléfono', footer_contact: 'Contacto',
    catalog_title: 'Catálogo', catalog_sub: 'Todo se fabrica a pedido y se puede personalizar en materiales, acabados y medidas.', filter_all: 'Todo',
    results_one: 'pieza', results_many: 'piezas', empty_catalog: 'No hay piezas que coincidan con tu búsqueda.',
    pd_back: 'Volver al catálogo', pd_custom: 'Personaliza tu pieza', pd_materials: 'Materiales', pd_dims: 'Dimensiones', pd_lead: 'Entrega', pd_lead_val: '6–8 semanas',
    pd_bespoke_hint: 'Elegiste medidas a medida: te contactaremos para definir las dimensiones exactas antes de fabricar.',
    pd_add: 'Añadir a la selección', pd_ar: 'Probar con realidad aumentada', pd_note: 'Pieza fabricada a mano bajo pedido. El precio final depende de las medidas y acabados elegidos.', pd_related: 'También del taller',
    pd_notfound: 'No encontramos esta pieza.',
    ar_title: 'Realidad aumentada', ar_requesting: 'Solicitando acceso a la cámara…', ar_hint: 'Arrastra el mueble para colocarlo · usa los botones para ajustar el tamaño',
    ar_nocam_t: 'Cámara no disponible', ar_nocam_d: 'Activa el permiso de cámara para ver el mueble en tu espacio. Mientras tanto, mostramos una sala de ejemplo.', ar_scale: 'Tamaño', ar_reset: 'Centrar', ar_close: 'Cerrar',
    cart_title: 'Tu selección', cart_empty: 'Aún no has añadido piezas.', cart_empty_cta: 'Ver catálogo', cart_subtotal: 'Subtotal estimado',
    cart_note: 'Cotización estimada, sujeta a medidas y acabados finales.', cart_checkout: 'Solicitar cotización',
    cart_thanks_t: '¡Solicitud enviada!', cart_thanks_d: 'Te contactaremos en menos de 48 h para afinar tu pedido y confirmar tiempos.', cart_close: 'Seguir explorando',
    cart_contact_title: 'Tus datos de contacto', cart_send_error: 'No se pudo enviar la solicitud. Inténtalo de nuevo.',
    about_kicker: 'El taller', about_title: 'Hacemos muebles que trabajan tan duro como tú', about_lead: 'Alvarsa nació en una nave llena de chispas, retazos de acero y madera recuperada. Seguimos ahí, soldando pieza por pieza.',
    about_body1: 'Somos una carpintería metálica: combinamos estructura de acero con madera maciza para hacer muebles honestos, robustos y de líneas limpias. Nada de tornillos escondidos que fallan al año.',
    about_body2: 'No producimos en serie. Cada encargo pasa por las mismas manos que diseñan, cortan y arman. Por eso podemos ajustar cualquier medida, acabado o material a lo que tu espacio necesita.',
    about_values_title: 'Cómo trabajamos', values: [{ ti: 'Materiales honestos', d: 'Acero al carbón, hierro fundido y maderas macizas o recuperadas. Se ven y se sienten como lo que son.' }, { ti: 'Hecho a mano', d: 'Cada soldadura y cada ensamble sale del taller, no de una línea de montaje.' }, { ti: 'A tu medida', d: 'Ajustamos dimensiones, acabados y herrajes sin costo de "personalización" inventado.' }],
    about_cta_title: 'Cuéntanos qué necesitas', about_cta_sub: 'Desde una repisa hasta amueblar un local completo. Empecemos por el catálogo.',
    contact_kicker: 'Hablemos', contact_title: 'Cuéntanos qué necesitas',
    contact_sub: 'Déjanos tus datos y el motivo. Te contactaremos para cotizar tu proyecto.',
    contact_name_label: 'Nombre', contact_name_ph: 'Tu nombre',
    contact_phone_label: 'Teléfono', contact_phone_ph: '+57 300 000 0000',
    contact_reason_label: 'Motivo', contact_reason_ph: '¿Qué pieza o proyecto tienes en mente? Cuéntanos medidas, espacio o fecha si ya las tienes.',
    contact_submit: 'Enviar solicitud', contact_error: 'No se pudo enviar. Revisa nombre y motivo.',
    contact_sent_t: '¡Gracias! Mensaje enviado', contact_sent_d: 'Recibimos tu solicitud. Te contactaremos en menos de 48 h.', contact_sent_btn: 'Enviar otro mensaje',
    contact_direct: 'O escríbenos directo', contact_hours: 'Lun a Vie · 9:00–18:00',
    search_ph: 'Buscar muebles…', lang_es_name: 'Español', lang_en_name: 'English',
    fav_title: 'Favoritos', fav_empty: 'Aún no has guardado piezas.', fav_empty_cta: 'Ver catálogo', fav_view: 'Ver pieza',
    // Cuenta / auth
    acc_title: 'Tu cuenta', acc_login: 'Iniciar sesión', acc_register: 'Crear cuenta', acc_logout: 'Cerrar sesión',
    acc_email: 'Correo', acc_password: 'Contraseña', acc_email_ph: 'tucorreo@ejemplo.com', acc_password_ph: 'Tu contraseña',
    acc_login_cta: 'Entrar', acc_register_cta: 'Registrarme', acc_have: '¿Ya tienes cuenta?', acc_no: '¿No tienes cuenta?',
    acc_signed_as: 'Sesión iniciada como', acc_role_admin: 'Administrador', acc_role_customer: 'Cliente',
    acc_admin_panel: 'Panel de administración', acc_err_creds: 'Correo o contraseña incorrectos.',
    acc_err_taken: 'Ese correo ya está registrado.', acc_err_input: 'Revisa los datos (contraseña mínimo 6 caracteres).',
    acc_err_generic: 'Algo salió mal. Inténtalo de nuevo.', acc_pw_hint: 'Mínimo 6 caracteres.',
    // Admin
    adm_kicker: 'Administración', adm_title: 'Crear producto', adm_sub: 'Registra una nueva pieza en el catálogo. Solo visible para administradores.',
    adm_created_count: 'piezas creadas en esta sesión', adm_section_basic: 'Información básica', adm_section_images: 'Imágenes',
    adm_section_custom: 'Personaliza tu pieza', adm_section_custom_sub: 'Selecciona las etiquetas de personalización disponibles para esta pieza.',
    adm_f_name: 'Nombre', adm_f_price: 'Precio (COP)', adm_f_dims: 'Dimensiones', adm_f_category: 'Categoría',
    adm_f_mat_es: 'Materiales (ES)', adm_f_mat_en: 'Materiales (EN)', adm_f_desc_es: 'Descripción (ES)', adm_f_desc_en: 'Descripción (EN)',
    adm_images_hint: 'Arrastra o elige varias fotos · JPG, PNG o WEBP', adm_images_btn: 'Elegir imágenes', adm_uploading: 'Subiendo…',
    adm_create: 'Crear producto', adm_update: 'Guardar cambios', adm_cancel: 'Cancelar', adm_creating: 'Guardando…',
    adm_products_title: 'Productos', adm_edit: 'Editar', adm_delete: 'Borrar', adm_new: 'Nuevo producto',
    adm_confirm_delete: '¿Borrar esta pieza?', adm_no_access: 'Necesitas una sesión de administrador para acceder a este panel.',
    adm_ok_created: 'Producto creado.', adm_ok_updated: 'Producto actualizado.', adm_err_save: 'No se pudo guardar el producto.',
    adm_metal: 'Acabado metal', adm_madera: 'Madera', adm_medida: 'Medida',
    adm_admin_fields: 'Campos internos (solo admin)', adm_cost: 'Costo interno (COP)', adm_notes: 'Notas de taller', adm_supplier: 'Ref. proveedor',
    adm_none: 'No hay productos todavía.', adm_back_store: 'Volver a la tienda',
  },
  en: {
    topbar: 'Handmade in the workshop · Bespoke pieces built to order',
    nav_home: 'Home', nav_catalog: 'Catalog', nav_about: 'The workshop', nav_bespoke: 'Made to order', nav_contact: 'Contact',
    hero_kicker: 'Metal & woodwork · since 2013', hero_title_1: 'Steel and wood', hero_title_2: 'with craft.',
    hero_sub: 'Industrial-style furniture, handmade piece by piece. We design and build it to your measurements.',
    hero_cta1: 'View catalog', hero_cta2: 'Order bespoke',
    cat_kicker: 'Collection', cat_title: 'Browse by category',
    feat_kicker: 'Selection', feat_title: 'Featured pieces', feat_link: 'See the full catalog', from: 'From', view_piece: 'View piece',
    arband_kicker: 'Augmented reality', arband_title: 'See how it would look in your ideal space', arband_sub: 'Place any Alvarsa piece in your room using your device camera and check size, proportion and style before you order it.', arband_cta: 'View in your space (AR)',
    moment_kicker: 'Piece of the month', moment_title: 'Our selection', moment_sub: 'Pieces that define the workshop craft. Comfort and structure that age well.', moment_cta: 'View piece',
    craft_quote: '"If it survives the workshop, it will last a lifetime in your home."', craft_by: '— The Alvarsa team',
    footer_addr: 'Cra. 50 #38-24, Itagüí, Antioquia', footer_rights: '© 2026 Alvarsa. All rights reserved.',
    footer_l_email: 'Email', footer_l_phone: 'Phone', footer_contact: 'Contact',
    catalog_title: 'Catalog', catalog_sub: 'Everything is built to order and can be customized in materials, finishes and size.', filter_all: 'All',
    results_one: 'piece', results_many: 'pieces', empty_catalog: 'No pieces match your search.',
    pd_back: 'Back to catalog', pd_custom: 'Customize your piece', pd_materials: 'Materials', pd_dims: 'Dimensions', pd_lead: 'Delivery', pd_lead_val: '6–8 weeks',
    pd_bespoke_hint: 'You chose bespoke sizing: we will contact you to define exact dimensions before building.',
    pd_add: 'Add to selection', pd_ar: 'View in your space (AR)', pd_note: 'Handmade to order. Final price depends on the measurements and finishes you choose.', pd_related: 'Also from the shop',
    pd_notfound: 'We could not find this piece.',
    ar_title: 'Augmented reality', ar_requesting: 'Requesting camera access…', ar_hint: 'Drag the piece to place it · use the buttons to resize',
    ar_nocam_t: 'Camera unavailable', ar_nocam_d: 'Allow camera access to see the piece in your space. For now, we show a sample room.', ar_scale: 'Size', ar_reset: 'Center', ar_close: 'Close',
    cart_title: 'Your selection', cart_empty: 'You haven’t added any pieces yet.', cart_empty_cta: 'View catalog', cart_subtotal: 'Estimated subtotal',
    cart_note: 'Estimated quote, subject to final measurements and finishes.', cart_checkout: 'Request a quote',
    cart_thanks_t: 'Request sent!', cart_thanks_d: 'We’ll reach out within 48 h to fine-tune your order and confirm timing.', cart_close: 'Keep exploring',
    cart_contact_title: 'Your contact details', cart_send_error: 'Could not send the request. Please try again.',
    about_kicker: 'The workshop', about_title: 'We make furniture that works as hard as you do', about_lead: 'Alvarsa started in a shop full of sparks, steel offcuts and reclaimed wood. We’re still there, welding one piece at a time.',
    about_body1: 'We’re a metal-and-wood workshop: we pair steel structure with solid wood to make honest, sturdy, clean-lined furniture. No hidden screws that give out in a year.',
    about_body2: 'We don’t mass-produce. Every commission passes through the same hands that design, cut and assemble it. That’s why we can adjust any measurement, finish or material to what your space needs.',
    about_values_title: 'How we work', values: [{ ti: 'Honest materials', d: 'Carbon steel, cast iron and solid or reclaimed wood. They look and feel like what they are.' }, { ti: 'Made by hand', d: 'Every weld and joint comes out of the workshop, not an assembly line.' }, { ti: 'To your measure', d: 'We adjust dimensions, finishes and hardware with no invented "customization" fee.' }],
    about_cta_title: 'Tell us what you need', about_cta_sub: 'From a single shelf to fitting out a whole space. Let’s start with the catalog.',
    contact_kicker: 'Let’s talk', contact_title: 'Tell us what you need',
    contact_sub: 'Leave your details and the reason for reaching out. We’ll get back to quote your project.',
    contact_name_label: 'Name', contact_name_ph: 'Your name',
    contact_phone_label: 'Phone', contact_phone_ph: '+57 300 000 0000',
    contact_reason_label: 'Reason', contact_reason_ph: 'What piece or project do you have in mind? Tell us sizes, space or date if you have them.',
    contact_submit: 'Send request', contact_error: 'Could not send. Check name and reason.',
    contact_sent_t: 'Thanks! Message sent', contact_sent_d: 'We got your request. We’ll be in touch within 48 h.', contact_sent_btn: 'Send another message',
    contact_direct: 'Or reach us directly', contact_hours: 'Mon to Fri · 9:00–18:00',
    search_ph: 'Search furniture…', lang_es_name: 'Español', lang_en_name: 'English',
    fav_title: 'Favorites', fav_empty: 'You haven’t saved any pieces yet.', fav_empty_cta: 'View catalog', fav_view: 'View piece',
    // Account / auth
    acc_title: 'Your account', acc_login: 'Sign in', acc_register: 'Create account', acc_logout: 'Sign out',
    acc_email: 'Email', acc_password: 'Password', acc_email_ph: 'you@example.com', acc_password_ph: 'Your password',
    acc_login_cta: 'Sign in', acc_register_cta: 'Register', acc_have: 'Already have an account?', acc_no: 'No account yet?',
    acc_signed_as: 'Signed in as', acc_role_admin: 'Administrator', acc_role_customer: 'Customer',
    acc_admin_panel: 'Admin panel', acc_err_creds: 'Wrong email or password.',
    acc_err_taken: 'That email is already registered.', acc_err_input: 'Check your details (password at least 6 characters).',
    acc_err_generic: 'Something went wrong. Please try again.', acc_pw_hint: 'At least 6 characters.',
    // Admin
    adm_kicker: 'Administration', adm_title: 'Create product', adm_sub: 'Register a new piece in the catalog. Only visible to administrators.',
    adm_created_count: 'pieces created this session', adm_section_basic: 'Basic information', adm_section_images: 'Images',
    adm_section_custom: 'Customize your piece', adm_section_custom_sub: 'Select the customization tags available for this piece.',
    adm_f_name: 'Name', adm_f_price: 'Price (COP)', adm_f_dims: 'Dimensions', adm_f_category: 'Category',
    adm_f_mat_es: 'Materials (ES)', adm_f_mat_en: 'Materials (EN)', adm_f_desc_es: 'Description (ES)', adm_f_desc_en: 'Description (EN)',
    adm_images_hint: 'Drag or choose several photos · JPG, PNG or WEBP', adm_images_btn: 'Choose images', adm_uploading: 'Uploading…',
    adm_create: 'Create product', adm_update: 'Save changes', adm_cancel: 'Cancel', adm_creating: 'Saving…',
    adm_products_title: 'Products', adm_edit: 'Edit', adm_delete: 'Delete', adm_new: 'New product',
    adm_confirm_delete: 'Delete this piece?', adm_no_access: 'You need an administrator session to access this panel.',
    adm_ok_created: 'Product created.', adm_ok_updated: 'Product updated.', adm_err_save: 'Could not save the product.',
    adm_metal: 'Metal finish', adm_madera: 'Wood', adm_medida: 'Size',
    adm_admin_fields: 'Internal fields (admin only)', adm_cost: 'Internal cost (COP)', adm_notes: 'Workshop notes', adm_supplier: 'Supplier ref.',
    adm_none: 'No products yet.', adm_back_store: 'Back to store',
  },
};

export type Dict = (typeof DICT)['es'];
